service: billing

frameworkVersion: '3'

package:
    individually: true
    excludeDevDependencies: true

plugins:
    - serverless-esbuild
    - serverless-offline

custom:
    serviceName: billing
    currentStage: ${opt:stage, 'billing'}
    esbild:
        bundle: true
        minify: true
        target: node16
        packager: yarn
        sourcemap: true
        sourcesContent: false

provider:
    name: aws
    runtime: nodejs16.x
    region: ap-southeast-2
    memorySize: 128
    environment:
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
        STRIPE_API_KEY: ${ssm:/app/${self:custom.currentStage}/${self:custom.serviceName}/STRIPE_API_KEY, null}
        STRIPE_WEBHOOK_SECRET: ${ssm:/app/${self:custom.currentStage}/${self:custom.serviceName}/STRIPE_WEBHOOK_SECRET, null}
    apiGateway:
        restApiId:
            'Fn::ImportValue': ${self:custom.serviceName}-ApiGatewayId-${self:custom.currentStage}
        restApiRootResourceId:
            'Fn::ImportValue': ${self:custom.serviceName}-ApiGatewayIdRootResourceId-${self:custom.currentStage}
        restApiResources:
            'billing':
                Fn::ImportValue: ${self:custom.serviceName}-ApiPath-Billing-${self:custom.currentStage}

functions:
    - ${file(./sls/routes/billing.yaml)}

resources:
    - ${file(./sls/api.yaml)}
    - ${file(./sls/routes.yaml)}
    - ${file(./sls/outputs.yaml)}
