service: billing

frameworkVersion: '3'

package:
    individually: false
    excludeDevDependencies: true

plugins:
    - serverless-dotenv-plugin
    - serverless-prune-plugin
    - serverless-esbuild
    - serverless-offline-ssm
    - serverless-offline

custom:
    dotenv:
        path: ../../
    prune:
        automatic: true
        number: 1
    serviceName: billing
    currentStage: ${opt:stage, 'billing'}
    esbuild:
        bundle: true
        minify: false
        target: node16
        packager: yarn
        sourcemap: true
        sourcesContent: true
        plugins: esbuild.plugins.js
    serverless-offline:
        httpPort: 4000
        lambdaPort: 4001
    serverless-offline-ssm:
        stages:
            - ${self:custom.serviceName}
        ssm:
            '/app/billing/billing/STRIPE_WEBHOOK_SECRET': ${env:STRIPE_WEBHOOK_SECRET}
            '/app/billing/billing/DB_URI': ${env:DB_URI}

provider:
    name: aws
    runtime: nodejs16.x
    region: ap-southeast-2
    memorySize: 128
    environment:
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
        STRIPE_WEBHOOK_SECRET: ${ssm:/app/${self:custom.currentStage}/${self:custom.serviceName}/STRIPE_WEBHOOK_SECRET}
        DB_URI: ${ssm:/app/${self:custom.currentStage}/${self:custom.serviceName}/DB_URI}
    apiGateway:
        restApiId:
            'Fn::ImportValue': ${self:custom.serviceName}-ApiGatewayId-${self:custom.currentStage}
        restApiRootResourceId:
            'Fn::ImportValue': ${self:custom.serviceName}-ApiGatewayIdRootResourceId-${self:custom.currentStage}
        restApiResources:
            'billing':
                Fn::ImportValue: ${self:custom.serviceName}-ApiPath-Billing-${self:custom.currentStage}

functions:
    - ${file(./sls/routes/billing.yaml)}

resources:
    - ${file(./sls/api.yaml)}
    - ${file(./sls/routes.yaml)}
    - ${file(./sls/outputs.yaml)}
