service: projects

frameworkVersion: '3'

package:
    individually: false
    excludeDevDependencies: true

plugins:
    - serverless-prune-plugin
    - serverless-esbuild
    - serverless-offline-ssm
    - serverless-offline

custom:
    prune:
        automatic: true
        number: 1
    serviceName: projects
    currentStage: ${opt:stage, 'projects'}
    esbuild:
        bundle: true
        minify: false
        target: node16
        packager: yarn
        sourcemap: true
        sourcesContent: true
        plugins: esbuild.plugins.js
    serverless-offline:
        httpPort: 6000
        lambdaPort: 6001
    serverless-offline-ssm:
        stages:
            - ${self:custom.serviceName}
        ssm:
            '/app/projects/projects/DB_URI': ${env:DB_URI}

provider:
    name: aws
    runtime: nodejs16.x
    region: ap-southeast-2
    memorySize: 128
    environment:
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
        DB_URI: ${ssm:/app/${self:custom.currentStage}/${self:custom.serviceName}/DB_URI}
    apiGateway:
        restApiId:
            'Fn::ImportValue': ${self:custom.serviceName}-ApiGatewayId-${self:custom.currentStage}
        restApiRootResourceId:
            'Fn::ImportValue': ${self:custom.serviceName}-ApiGatewayIdRootResourceId-${self:custom.currentStage}
        restApiResources:
            'projects':
                Fn::ImportValue: ${self:custom.serviceName}-ApiPath-Projects-${self:custom.currentStage}
            'projects/{projectId}':
                Fn::ImportValue: ${self:custom.serviceName}-ApiPath-ProjectsById-${self:custom.currentStage}
            'projects/{projectId}/targets':
                Fn::ImportValue: ${self:custom.serviceName}-ApiPath-Targets-${self:custom.currentStage}
            'projects/{projectId}/targets/{targetId}':
                Fn::ImportValue: ${self:custom.serviceName}-ApiPath-TargetsById-${self:custom.currentStage}
            'projects/{projectId}/variants':
                Fn::ImportValue: ${self:custom.serviceName}-ApiPath-Variants-${self:custom.currentStage}
            'projects/{projectId}/variants/{variantId}':
                Fn::ImportValue: ${self:custom.serviceName}-ApiPath-VariantsById-${self:custom.currentStage}

functions:
    - ${file(./sls/routes/projects.yaml)}
    - ${file(./sls/routes/targets.yaml)}
    - ${file(./sls/routes/variants.yaml)}

resources:
    - ${file(./sls/api.yaml)}
    - ${file(./sls/routes.yaml)}
    - ${file(./sls/outputs.yaml)}
