updateSettings:
    handler: src/settings/update-settings/handler.updateSettings
    events:
        - http:
              method: PUT
              path: /api/v1/projects/{projectId}/features/{featureId}/settings/{settingsId}
              authorizer:
                  type: CUSTOM
                  authorizerId:
                      Fn::ImportValue: ${self:custom.serviceName}-ApiGatewayAuthorizerId-${self:custom.currentStage}

retrieveSettings:
    handler: src/settings/retrieve-settings/handler.retrieveSettings
    events:
        - http:
              method: GET
              path: /api/v1/projects/{projectId}/features/{featureId}/settings/{settingsId}
              authorizer:
                  type: CUSTOM
                  authorizerId:
                      Fn::ImportValue: ${self:custom.serviceName}-ApiGatewayAuthorizerId-${self:custom.currentStage}
