service: environments

frameworkVersion: '3'

package:
    individually: true
    excludeDevDependencies: true

plugins:
    - serverless-esbuild
    - serverless-offline

custom:
    esbild:
        bundle: true
        minify: true
        target: node16
        packager: yarn
        sourcemap: true
        sourcesContent: false

provider:
    name: aws
    runtime: nodejs16.x
    memorySize: 128
    apiGateway:
        minimumCompressionSize: 1024
    httpApi:
        cors: true
    stage: ${opt:stage}
    environment:
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'

    region: ap-southeast-2

functions:
    hello:
        handler: src/handler.hello
