service: features

frameworkVersion: '3'

package:
    individually: false
    excludeDevDependencies: true

plugins:
    - serverless-prune-plugin
    - serverless-esbuild
    - serverless-offline-ssm
    - serverless-offline

custom:
    prune:
        automatic: true
        number: 1
    serviceName: features
    currentStage: ${opt:stage, 'features'}
    esbuild:
        bundle: true
        minify: false
        target: node16
        packager: yarn
        sourcemap: true
        sourcesContent: false
        plugins: esbuild.plugins.js
    serverless-offline:
        httpPort: 9000
        lambdaPort: 9001
    serverless-offline-ssm:
        stages:
            - ${self:custom.serviceName}
        ssm:
            '/app/features/features/DB_URI': ${env:DB_URI}

provider:
    name: aws
    runtime: nodejs16.x
    region: ap-southeast-2
    memorySize: 128
    environment:
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
        DB_URI: ${ssm:/app/${self:custom.currentStage}/${self:custom.serviceName}/DB_URI}
    apiGateway:
        restApiId:
            'Fn::ImportValue': ${self:custom.serviceName}-ApiGatewayId-${self:custom.currentStage}
        restApiRootResourceId:
            'Fn::ImportValue': ${self:custom.serviceName}-ApiGatewayIdRootResourceId-${self:custom.currentStage}
        restApiResources:
            'features':
                Fn::ImportValue: ${self:custom.serviceName}-ApiPath-Features-${self:custom.currentStage}
            'features/{featureId}':
                Fn::ImportValue: ${self:custom.serviceName}-ApiPath-FeaturesById-${self:custom.currentStage}
            'features/{featureId}/conditionsets':
                Fn::ImportValue: ${self:custom.serviceName}-ApiPath-ConditionSets-${self:custom.currentStage}
            'features/{featureId}/conditionsets/{csetId}':
                Fn::ImportValue: ${self:custom.serviceName}-ApiPath-ConditionSetsById-${self:custom.currentStage}
            'features/{featureId}/settings':
                Fn::ImportValue: ${self:custom.serviceName}-ApiPath-Settings-${self:custom.currentStage}
            'features/{featureId}/settings/{settingsId}':
                Fn::ImportValue: ${self:custom.serviceName}-ApiPath-SettingsById-${self:custom.currentStage}

functions:
    - ${file(./sls/routes/feature.yaml)}
    - ${file(./sls/routes/csets.yaml)}
    - ${file(./sls/routes/settings.yaml)}

resources:
    - ${file(./sls/api.yaml)}
    - ${file(./sls/routes.yaml)}
    - ${file(./sls/outputs.yaml)}
